### ISSUE TITLE
Feature request: Editing of null fields in the table view

### ISSUE THREAD

**Issue by NjengaFelix** [myappgini/tvedit#1]
The field editor in table view works fine on fields that have values. 
My feature request is on editing of null fields in the table view as the current working situation only 
allows updating of fields that already have values. @landinialejandro 
![Screenshot (55)](https://user-images.githubusercontent.com/32095327/83850563-c9ce8f80-a719-11ea-8ac0-468a63f41267.png)

**Comment by landinialejandro** [comment]
Hi! i was added this functionality.
let me know!
Thanks
