### ISSUE TITLE
Update request: Prevent editing of read only rows/records

### ISSUE THREAD

**Issue by NjengaFelix** [myappgini/tvedit#2]
Your feature for updating rows does not prevent users from updating rows/records. It doesn't prevent users from updating read only rows/records

**Comment by landinialejandro** [comment]
Hi!
This issue is corrected, the possibility of selecting disabled fields is added to the edition.
Please let me know.

**Comment by NjengaFelix** [comment]
#1 
Sorry for the late reply. I am now able to prevent the user from editing certain rows/records. Thank you so much for the update. Here is an example of the update

![Screenshot (6)](https://user-images.githubusercontent.com/32095327/93092696-6fde4e00-f6a8-11ea-94fc-10ae51ccb8f3.png)

I am preventing the user from editing the following rows 'student_ID','first_name', 'last_name', 'total', 'mean'

![Screenshot (5)](https://user-images.githubusercontent.com/32095327/93092842-a025ec80-f6a8-11ea-9125-85f1d363d7eb.png)

**Comment by NjengaFelix** [comment]
#1 
Thank you so much for the update. In my example below column **grade** is a null field

![Screenshot (5)](https://user-images.githubusercontent.com/32095327/93093451-60133980-f6a9-11ea-8152-3f652f946257.png)
