### ISSUE TITLE
Drop down menu (look up field display) on table view

### ISSUE THREAD

**Issue by NjengaFelix** [myappgini/tvedit#3]
Can you add a drop down menu to the look up field column(s) on the table view. i.e
On the screenshot below. The class column is a look up field. I don't want the user to input his/her own class value, but to select the specific class through a drop down menu

![Screenshot (8)](https://user-images.githubusercontent.com/32095327/93095359-a9fd1f00-f6ab-11ea-8314-aabe9c0738f1.png)

Still at the screenshot above, the gender column is an options list column. Where by the user only puts in values from a drop down menu.

**Comment by landinialejandro** [comment]
I haven't done any implementation about it yet. I am very sorry for the delay in responding.
